version: 2.1

commands:
  destroy_environment:
    steps:
      - run: 
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --stack-name Minha-Stack-${CIRCLE_WORKFLOW_ID}

workflows:
  my_workflow:
    jobs:
      - create_infrastructure

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Create Infrastructure Using CloudFormation"
          command: | 
            aws cloudformation deploy \
            --template-file template.yml --stack-name Minha-Stack-${CIRCLE_WORKFLOW_ID}
      - run: 
          name: simulate error
          command: |
            return 1
      - when: 
          condition: on_fail
          steps:
            - destroy_environment
        