version: 2.1

workflows:
  my_workflow:
    jobs:
      - create_infrastructure

commands:
  destroy_environment:
    steps:
      - run: 
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --stack-name Minha-Stack-${CIRCLE_WORKFLOW_ID}

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Create Infrastructure Using CloudFormation"
          command: | 
            aws cloudformation deploy \
            --template-file template.yml --stack-name Minha-Stack-${CIRCLE_WORKFLOW_ID}
      - run: return 1
      - destroy_environment
          when: on_fail