version: 2.1

workflows:
  my_workflow:
    jobs:
      - create_infrastructure

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Create Infrastructure Using CloudFormation"
          command: | 
          aws cloudformation deploy \
            --template-file template.yml --stack-name Minha_Stack